name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  IMAGE_NAME: autopg
  GO_VERSION: 1.25

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.OS }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.OS }}-go-

      - name: Go mod download
        run: go mod download

      - name: Run go vet
        run: go vet ./...

      - name: Build binary (linux)
        run: |
          CGO_ENABLED=1 GOOS=linux go build -ldflags="-s -w" -o bin/autopg ./main.go

      - name: Build Docker image
        run: |
          docker build --file Dockerfile --tag $IMAGE_NAME:latest .

      - name: Login to GitHub Container Registry
        if: github.token
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Tag image for GHCR
        run: |
          ghcr_image=ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}:latest
          docker tag $IMAGE_NAME:latest $ghcr_image
          docker tag $IMAGE_NAME:latest ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}:${{ github.sha }}

      - name: Push to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}:latest
          docker push ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}:${{ github.sha }}

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.59.0
          args: run ./...
